name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Clone SACGenCode.github.io Repository
        run: git clone https://github.com/SACGenCode/SACGenCode.github.io.git SACGenCode.github.io

      - name: Copy Build to SACGenCode.github.io
        run: cp -r build/* SACGenCode.github.io/

      - name: Commit and Push Changes
        working-directory: ./SACGenCode.github.io
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update build from main repository"
          git push origin main
